/* Generated By:JavaCC: Do not edit this line. acmeParserTreeConstants.java Version 5.0 */
public interface acmeParserTreeConstants
{
  public int JJTFILENAME = 0;
  public int JJTPARSE_ACMEDESIGN = 1;
  public int JJTFAMILYDECLARATION = 2;
  public int JJTFAMILYBODY = 3;
  public int JJTTYPEDECLARATION = 4;
  public int JJTELEMENTTYPEDECLARATION = 5;
  public int JJTPARSE_DESCRIPTIONS = 6;
  public int JJTPARSE_DESCRIPTIONSCONN = 7;
  public int JJTPARSE_DESCRIPTIONSCOMP = 8;
  public int JJTELEMENTPROTOTYPEDECLARATION = 9;
  public int JJTCOMPONENTTYPEDECLARATION = 10;
  public int JJTGROUPTYPEDECLARATION = 11;
  public int JJTCONNECTORTYPEDECLARATION = 12;
  public int JJTPORTTYPEDECLARATION = 13;
  public int JJTROLETYPEDECLARATION = 14;
  public int JJTLOOKUP_TYPEBYNAME = 15;
  public int JJTLOOKUP_ARBITRARYTYPEBYNAME = 16;
  public int JJTSYSTEMDECLARATION = 17;
  public int JJTSYSTEMBODY = 18;
  public int JJTSYSTEMSTRUCTURE = 19;
  public int JJTPARSE_ELEMENTPROTOTYPEDESCRIPTION = 20;
  public int JJTGROUPDECLARATION = 21;
  public int JJTPARSE_GROUPDESCRIPTION = 22;
  public int JJTCOMPONENTDECLARATION = 23;
  public int JJTCOMPONENTSBLOCK = 24;
  public int JJTPARSE_COMPONENTDESCRIPTION = 25;
  public int JJTPARSE_INNERPORTDESCRIPTION = 26;
  public int JJTCONNECTORDECLARATION = 27;
  public int JJTCONNECTORSBLOCK = 28;
  public int JJTPARSE_CONNECTORDESCRIPTION = 29;
  public int JJTPARSE_INNERROLEDESCRIPTION = 30;
  public int JJTPORTDECLARATION = 31;
  public int JJTPORTSBLOCK = 32;
  public int JJTPARSE_PORTROLEDESCRIPTION = 33;
  public int JJTROLEDECLARATION = 34;
  public int JJTMEMBERSBLOCK = 35;
  public int JJTQUALIFIEDREFERENCE = 36;
  public int JJTROLESBLOCK = 37;
  public int JJTPARSE_PROPERTIESCHOICE = 38;
  public int JJTATTACHMENTSDECLARATION = 39;
  public int JJTPROPERTYDECLARATION = 40;
  public int JJTPROPERTIESBLOCK = 41;
  public int JJTPARSE_PROPERTYDESCRIPTION = 42;
  public int JJTPROPERTYTYPEDECLARATION = 43;
  public int JJTPROPERTYTYPEDESCRIPTION = 44;
  public int JJTPARSE_RECORDFIELDDESCRIPTION = 45;
  public int JJTPROPERTYVALUEDECLARATION = 46;
  public int JJTACMESETVALUE = 47;
  public int JJTACMESEQUENCEVALUE = 48;
  public int JJTACMERECORDVALUE = 49;
  public int JJTRECORDFIELDVALUE = 50;
  public int JJTREPRESENTATIONDECLARATION = 51;
  public int JJTBINDINGSMAPDECLARATION = 52;
  public int JJTBINDINGDECLARATION = 53;
  public int JJTDESIGNANALYSISDECLARATION = 54;
  public int JJTPARSE_DESIGNRULE = 55;
  public int JJTDESIGNRULEEXPRESSION = 56;
  public int JJTQUANTIFIEDEXPRESSION = 57;
  public int JJTBOOLEANEXPRESSION = 58;
  public int JJTOREXPRESSION = 59;
  public int JJTIMPLIESEXPRESSION = 60;
  public int JJTIFFEXPRESSION = 61;
  public int JJTEQUALITYEXPRESSION = 62;
  public int JJTRELATIONALEXPRESSION = 63;
  public int JJTADDITIVEEXPRESSION = 64;
  public int JJTMULTIPLICATIVEEXPRESSION = 65;
  public int JJTUNARYEXPRESSION = 66;
  public int JJTPRIMITIVEEXPRESSION = 67;
  public int JJTREFERENCE = 68;
  public int JJTJAVAMETHODCALLEXPR = 69;
  public int JJTLITERALCONSTANT = 70;
  public int JJTACTUALPARAMS = 71;
  public int JJTFORMALPARAMS = 72;
  public int JJTACTUALPARAM = 73;
  public int JJTFORMALPARAM = 74;
  public int JJTSETEXPRESSION = 75;
  public int JJTLITERALSET = 76;
  public int JJTSETCONSTRUCTOR = 77;
  public int JJTRECORDTYPE = 78;
  public int JJTRECORDITEM = 79;
  public int JJTSETTYPE = 80;
  public int JJTSEQUENCETYPE = 81;
  public int JJTSIGNATURE = 82;
  public int JJTTYPE = 83;
  public int JJTPRIMITIVETYPE = 84;
  public int JJTELEMENT = 85;
  public int JJTCOMPOUNDELEMENT = 86;
  public int JJTSET = 87;
  public int JJTRECORD = 88;
  public int JJTSEQUENCE = 89;


  public String[] jjtNodeName = {
    "Filename",
    "parse_AcmeDesign",
    "FamilyDeclaration",
    "FamilyBody",
    "TypeDeclaration",
    "ElementTypeDeclaration",
    "parse_descriptions",
    "parse_descriptionsConn",
    "parse_descriptionsComp",
    "ElementProtoTypeDeclaration",
    "ComponentTypeDeclaration",
    "GroupTypeDeclaration",
    "ConnectorTypeDeclaration",
    "PortTypeDeclaration",
    "RoleTypeDeclaration",
    "lookup_TypeByName",
    "lookup_arbitraryTypeByName",
    "SystemDeclaration",
    "SystemBody",
    "SystemStructure",
    "parse_ElementProtoTypeDescription",
    "GroupDeclaration",
    "parse_GroupDescription",
    "ComponentDeclaration",
    "ComponentsBlock",
    "parse_ComponentDescription",
    "parse_InnerPortDescription",
    "ConnectorDeclaration",
    "ConnectorsBlock",
    "parse_ConnectorDescription",
    "parse_InnerRoleDescription",
    "PortDeclaration",
    "PortsBlock",
    "parse_PortRoleDescription",
    "RoleDeclaration",
    "MembersBlock",
    "QualifiedReference",
    "RolesBlock",
    "parse_PropertiesChoice",
    "AttachmentsDeclaration",
    "PropertyDeclaration",
    "PropertiesBlock",
    "parse_PropertyDescription",
    "PropertyTypeDeclaration",
    "PropertyTypeDescription",
    "parse_RecordFieldDescription",
    "PropertyValueDeclaration",
    "AcmeSetValue",
    "AcmeSequenceValue",
    "AcmeRecordValue",
    "RecordFieldValue",
    "RepresentationDeclaration",
    "BindingsMapDeclaration",
    "BindingDeclaration",
    "DesignAnalysisDeclaration",
    "parse_DesignRule",
    "DesignRuleExpression",
    "QuantifiedExpression",
    "BooleanExpression",
    "OrExpression",
    "ImpliesExpression",
    "IffExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PrimitiveExpression",
    "Reference",
    "JavaMethodCallExpr",
    "LiteralConstant",
    "ActualParams",
    "FormalParams",
    "ActualParam",
    "FormalParam",
    "SetExpression",
    "LiteralSet",
    "SetConstructor",
    "RecordType",
    "RecordItem",
    "SetType",
    "SequenceType",
    "Signature",
    "Type",
    "PrimitiveType",
    "Element",
    "CompoundElement",
    "Set",
    "Record",
    "Sequence",
  };
}
/* JavaCC - OriginalChecksum=2b9ad380bc273fde2f22a21cb9a34a40 (do not edit this line) */
