/* Generated By:JJTree: Do not edit this line. ASTAcmeRecordValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAcmeRecordValue extends SimpleNode {
  public ASTAcmeRecordValue(int id) {
    super(id);
  }

  public ASTAcmeRecordValue(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4424b0ab0d54ada92d99a62a9706f818 (do not edit this line) */
