/* Generated By:JJTree: Do not edit this line. ASTAcmeSetValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAcmeSetValue extends SimpleNode {
  public ASTAcmeSetValue(int id) {
    super(id);
  }

  public ASTAcmeSetValue(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=496239e580166838dc0d40cba20a465d (do not edit this line) */
