/* Generated By:JJTree: Do not edit this line. ASTActualParam.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActualParam extends SimpleNode {
  public ASTActualParam(int id) {
    super(id);
  }

  public ASTActualParam(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a91842ab75c28d71eb57c48d602a7fc (do not edit this line) */
