/* Generated By:JJTree: Do not edit this line. ASTAttachmentsDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAttachmentsDeclaration extends SimpleNode {
  public ASTAttachmentsDeclaration(int id) {
    super(id);
  }

  public ASTAttachmentsDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1cb191a323f4a0b9d3f2fa6e96982adb (do not edit this line) */
