/* Generated By:JJTree: Do not edit this line. ASTAcmeSequenceValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAcmeSequenceValue extends SimpleNode {
  public ASTAcmeSequenceValue(int id) {
    super(id);
  }

  public ASTAcmeSequenceValue(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ee0f4cc275414d40412e0e1b9a9d175b (do not edit this line) */
