/* Generated By:JJTree: Do not edit this line. ASTActualParams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActualParams extends SimpleNode {
  public ASTActualParams(int id) {
    super(id);
  }

  public ASTActualParams(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2061765931f288765e305b2e0567098d (do not edit this line) */
