/* Generated By:JJTree: Do not edit this line. ASTBindingsMapDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBindingsMapDeclaration extends SimpleNode {
  public ASTBindingsMapDeclaration(int id) {
    super(id);
  }

  public ASTBindingsMapDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48bb1e0fdb5aa126b8b4a1db2fdc0117 (do not edit this line) */
