/* Generated By:JJTree: Do not edit this line. ASTBindingDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBindingDeclaration extends SimpleNode {
  public ASTBindingDeclaration(int id) {
    super(id);
  }

  public ASTBindingDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c2ceceaeabee4e34f42f361304d2a00 (do not edit this line) */
