/* Generated By:JJTree: Do not edit this line. ASTBooleanExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBooleanExpression extends SimpleNode {
  public ASTBooleanExpression(int id) {
    super(id);
  }

  public ASTBooleanExpression(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=941d479ce5a80f040ab5c8a369d0ab3f (do not edit this line) */
