/* Generated By:JJTree: Do not edit this line. ASTComponentsBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComponentsBlock extends SimpleNode {
  public ASTComponentsBlock(int id) {
    super(id);
  }

  public ASTComponentsBlock(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f5169305ec994af81e572cf0685b420 (do not edit this line) */
