/* Generated By:JJTree: Do not edit this line. ASTComponentTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComponentTypeDeclaration extends SimpleNode {
  public ASTComponentTypeDeclaration(int id) {
    super(id);
  }

  public ASTComponentTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=507737cdb042c3d5b87bb0683a213f18 (do not edit this line) */
