/* Generated By:JJTree: Do not edit this line. ASTConnectorTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConnectorTypeDeclaration extends SimpleNode {
  public ASTConnectorTypeDeclaration(int id) {
    super(id);
  }

  public ASTConnectorTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b31f99e01cf65e9ca664df3e7e0a2fdd (do not edit this line) */
