/* Generated By:JJTree: Do not edit this line. ASTComponentDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComponentDeclaration extends SimpleNode {
  public ASTComponentDeclaration(int id) {
    super(id);
  }

  public ASTComponentDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a5db346aa6cb2253eba10572d87c364 (do not edit this line) */
