/* Generated By:JJTree: Do not edit this line. ASTCompoundElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCompoundElement extends SimpleNode {
  public ASTCompoundElement(int id) {
    super(id);
  }

  public ASTCompoundElement(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf5276adb6d036201da23329f7aacb58 (do not edit this line) */
