/* Generated By:JJTree: Do not edit this line. ASTDesignAnalysisDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDesignAnalysisDeclaration extends SimpleNode {
  public ASTDesignAnalysisDeclaration(int id) {
    super(id);
  }

  public ASTDesignAnalysisDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de2ebcc1ac6e0a2f5d7e7ca95e0baffc (do not edit this line) */
