/* Generated By:JJTree: Do not edit this line. ASTDesignRuleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDesignRuleExpression extends SimpleNode {
  public ASTDesignRuleExpression(int id) {
    super(id);
  }

  public ASTDesignRuleExpression(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b012cf0cb9bf1c8cef97f0377c22916e (do not edit this line) */
