/* Generated By:JJTree: Do not edit this line. ASTElementProtoTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElementProtoTypeDeclaration extends SimpleNode {
  public ASTElementProtoTypeDeclaration(int id) {
    super(id);
  }

  public ASTElementProtoTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b09e7939485a61db56ce9588b2fb8e0 (do not edit this line) */
