/* Generated By:JJTree: Do not edit this line. ASTElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElement extends SimpleNode {
  public ASTElement(int id) {
    super(id);
  }

  public ASTElement(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=217277ea2d0469bd7b11588bbc63705c (do not edit this line) */
