/* Generated By:JJTree: Do not edit this line. ASTElementTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElementTypeDeclaration extends SimpleNode {
  public ASTElementTypeDeclaration(int id) {
    super(id);
  }

  public ASTElementTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a74e8acdd06108fc00973a35ca17a70 (do not edit this line) */
