/* Generated By:JJTree: Do not edit this line. ASTFamilyBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFamilyBody extends SimpleNode {
  public ASTFamilyBody(int id) {
    super(id);
  }

  public ASTFamilyBody(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4ea54f7d8be43c1388874c0a2259553 (do not edit this line) */
