/* Generated By:JJTree: Do not edit this line. ASTFormalParam.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFormalParam extends SimpleNode {
  public ASTFormalParam(int id) {
    super(id);
  }

  public ASTFormalParam(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29e915d723d8c99492eb94a181d11529 (do not edit this line) */
