/* Generated By:JJTree: Do not edit this line. ASTFamilyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFamilyDeclaration extends SimpleNode {
  public ASTFamilyDeclaration(int id) {
    super(id);
  }

  public ASTFamilyDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5ad8ff5c23bf507f279283f99a226c6 (do not edit this line) */
