/* Generated By:JJTree: Do not edit this line. ASTFormalParams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFormalParams extends SimpleNode {
  public ASTFormalParams(int id) {
    super(id);
  }

  public ASTFormalParams(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab38b970b0d284c351604830d79d7a7f (do not edit this line) */
