/* Generated By:JJTree: Do not edit this line. ASTFilename.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFilename extends SimpleNode {
  public ASTFilename(int id) {
    super(id);
  }

  public ASTFilename(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81f7178b76699aa0eee6856c045ecb44 (do not edit this line) */
