/* Generated By:JJTree: Do not edit this line. ASTGroupDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGroupDeclaration extends SimpleNode {
  public ASTGroupDeclaration(int id) {
    super(id);
  }

  public ASTGroupDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e7a575a3ab93c5f6985c16230f35f86 (do not edit this line) */
