/* Generated By:JJTree: Do not edit this line. ASTGroupTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGroupTypeDeclaration extends SimpleNode {
  public ASTGroupTypeDeclaration(int id) {
    super(id);
  }

  public ASTGroupTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c206a9d40ab3ac26f6f876b94d50b0f (do not edit this line) */
