/* Generated By:JJTree: Do not edit this line. ASTImpliesExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImpliesExpression extends SimpleNode {
  public ASTImpliesExpression(int id) {
    super(id);
  }

  public ASTImpliesExpression(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2635a4e919d2d21a24df0f3e014d78fb (do not edit this line) */
