/* Generated By:JJTree: Do not edit this line. ASTJavaMethodCallExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJavaMethodCallExpr extends SimpleNode {
  public ASTJavaMethodCallExpr(int id) {
    super(id);
  }

  public ASTJavaMethodCallExpr(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7778df118801e9da6a9c8cf2c762423 (do not edit this line) */
