/* Generated By:JJTree: Do not edit this line. ASTlookup_TypeByName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlookup_TypeByName extends SimpleNode {
  public ASTlookup_TypeByName(int id) {
    super(id);
  }

  public ASTlookup_TypeByName(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b716d76241367711686978f11473df27 (do not edit this line) */
