/* Generated By:JJTree: Do not edit this line. ASTlookup_arbitraryTypeByName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlookup_arbitraryTypeByName extends SimpleNode {
  public ASTlookup_arbitraryTypeByName(int id) {
    super(id);
  }

  public ASTlookup_arbitraryTypeByName(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06e1174f78aeb3e735e4ac93ba28f0f9 (do not edit this line) */
