/* Generated By:JJTree: Do not edit this line. ASTLiteralConstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteralConstant extends SimpleNode {
  public ASTLiteralConstant(int id) {
    super(id);
  }

  public ASTLiteralConstant(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c40b85abcd2c3ed362d82c079b67f93 (do not edit this line) */
