/* Generated By:JJTree: Do not edit this line. ASTLiteralSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteralSet extends SimpleNode {
  public ASTLiteralSet(int id) {
    super(id);
  }

  public ASTLiteralSet(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c732cf78847006568075a7e3eb79b2a3 (do not edit this line) */
