/* Generated By:JJTree: Do not edit this line. ASTMembersBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMembersBlock extends SimpleNode {
  public ASTMembersBlock(int id) {
    super(id);
  }

  public ASTMembersBlock(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=78b713d53a58b351eb5c09fa07ee6db1 (do not edit this line) */
