/* Generated By:JJTree: Do not edit this line. ASTone_line.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTone_line extends SimpleNode {
  public ASTone_line(int id) {
    super(id);
  }

  public ASTone_line(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3b9c0d8980cfb87c04bb51c8287a74d (do not edit this line) */
