/* Generated By:JJTree: Do not edit this line. ASTPortsBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPortsBlock extends SimpleNode {
  public ASTPortsBlock(int id) {
    super(id);
  }

  public ASTPortsBlock(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d262b341e7842de4f139a7c03f0ad5fa (do not edit this line) */
