/* Generated By:JJTree: Do not edit this line. ASTparse_ElementProtoTypeDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_ElementProtoTypeDescription extends SimpleNode {
  public ASTparse_ElementProtoTypeDescription(int id) {
    super(id);
  }

  public ASTparse_ElementProtoTypeDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af8134ef641a8bc5913f73e5aff909a5 (do not edit this line) */
