/* Generated By:JJTree: Do not edit this line. ASTparse_descriptionsComp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_descriptionsComp extends SimpleNode {
  public ASTparse_descriptionsComp(int id) {
    super(id);
  }

  public ASTparse_descriptionsComp(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb2018b645b875e539c7ee0f395fba51 (do not edit this line) */
