/* Generated By:JJTree: Do not edit this line. ASTPropertyTypeDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPropertyTypeDescription extends SimpleNode {
  public ASTPropertyTypeDescription(int id) {
    super(id);
  }

  public ASTPropertyTypeDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e2054f0fe8baa5b5cb95ea4e6ca63d7 (do not edit this line) */
