/* Generated By:JJTree: Do not edit this line. ASTparse_PropertyDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_PropertyDescription extends SimpleNode {
  public ASTparse_PropertyDescription(int id) {
    super(id);
  }

  public ASTparse_PropertyDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c54a254210725cac2ee91071ea2ceab (do not edit this line) */
