/* Generated By:JJTree: Do not edit this line. ASTPropertyTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPropertyTypeDeclaration extends SimpleNode {
  public ASTPropertyTypeDeclaration(int id) {
    super(id);
  }

  public ASTPropertyTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f942e49b423642ea42ad5ccae427dee (do not edit this line) */
