/* Generated By:JJTree: Do not edit this line. ASTPrimitiveExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimitiveExpression extends SimpleNode {
  public ASTPrimitiveExpression(int id) {
    super(id);
  }

  public ASTPrimitiveExpression(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46ee05eff3834f226d643a724015df28 (do not edit this line) */
