/* Generated By:JJTree: Do not edit this line. ASTparse_descriptions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_descriptions extends SimpleNode {
  public ASTparse_descriptions(int id) {
    super(id);
  }

  public ASTparse_descriptions(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db10bc5e88d1711a70b469d8144e60cb (do not edit this line) */
