/* Generated By:JJTree: Do not edit this line. ASTPortDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPortDeclaration extends SimpleNode {
  public ASTPortDeclaration(int id) {
    super(id);
  }

  public ASTPortDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd34db558163c8804046d319caebc2f7 (do not edit this line) */
