/* Generated By:JJTree: Do not edit this line. ASTPropertyValueDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPropertyValueDeclaration extends SimpleNode {
  public ASTPropertyValueDeclaration(int id) {
    super(id);
  }

  public ASTPropertyValueDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=664d1d1bd7a1ad512638223a01bc0316 (do not edit this line) */
