/* Generated By:JJTree: Do not edit this line. ASTPropertiesBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPropertiesBlock extends SimpleNode {
  public ASTPropertiesBlock(int id) {
    super(id);
  }

  public ASTPropertiesBlock(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b35f4699012d0acdd21b7df3b459480 (do not edit this line) */
