/* Generated By:JJTree: Do not edit this line. ASTparse_RecordFieldDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_RecordFieldDescription extends SimpleNode {
  public ASTparse_RecordFieldDescription(int id) {
    super(id);
  }

  public ASTparse_RecordFieldDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d61be7acebd311d8bc712f2f62a161b3 (do not edit this line) */
