/* Generated By:JJTree: Do not edit this line. ASTPropertyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPropertyDeclaration extends SimpleNode {
  public ASTPropertyDeclaration(int id) {
    super(id);
  }

  public ASTPropertyDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c49e4c9801a45475c8a773f4fbfe407b (do not edit this line) */
