/* Generated By:JJTree: Do not edit this line. ASTparse_ComponentDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_ComponentDescription extends SimpleNode {
  public ASTparse_ComponentDescription(int id) {
    super(id);
  }

  public ASTparse_ComponentDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97702a71436f9100a7a78c470fffa082 (do not edit this line) */
