/* Generated By:JJTree: Do not edit this line. ASTparse_InnerRoleDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_InnerRoleDescription extends SimpleNode {
  public ASTparse_InnerRoleDescription(int id) {
    super(id);
  }

  public ASTparse_InnerRoleDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75122412637614985cf4a43d02b2aec4 (do not edit this line) */
