/* Generated By:JJTree: Do not edit this line. ASTparse_descriptionsConn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_descriptionsConn extends SimpleNode {
  public ASTparse_descriptionsConn(int id) {
    super(id);
  }

  public ASTparse_descriptionsConn(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=baf3f50f68adb0580b9680bbfb2836a3 (do not edit this line) */
