/* Generated By:JJTree: Do not edit this line. ASTparse_PropertiesChoice.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_PropertiesChoice extends SimpleNode {
  public ASTparse_PropertiesChoice(int id) {
    super(id);
  }

  public ASTparse_PropertiesChoice(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a413b4a6143b42cacf042379134940cc (do not edit this line) */
