/* Generated By:JJTree: Do not edit this line. ASTparse_AcmeDesign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_AcmeDesign extends SimpleNode {
  public ASTparse_AcmeDesign(int id) {
    super(id);
  }

  public ASTparse_AcmeDesign(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=39683793377248f1f1f98629fc22b112 (do not edit this line) */
