/* Generated By:JJTree: Do not edit this line. ASTparse_ConnectorDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_ConnectorDescription extends SimpleNode {
  public ASTparse_ConnectorDescription(int id) {
    super(id);
  }

  public ASTparse_ConnectorDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2824d43a544e37e20672bc1b89077a8d (do not edit this line) */
