/* Generated By:JJTree: Do not edit this line. ASTPortTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPortTypeDeclaration extends SimpleNode {
  public ASTPortTypeDeclaration(int id) {
    super(id);
  }

  public ASTPortTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3e04e9282a38511e4177a2d9423fb0f2 (do not edit this line) */
