/* Generated By:JJTree: Do not edit this line. ASTparse_InnerPortDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_InnerPortDescription extends SimpleNode {
  public ASTparse_InnerPortDescription(int id) {
    super(id);
  }

  public ASTparse_InnerPortDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5df7b79f1b94a48abec51a9c854b5ea1 (do not edit this line) */
