/* Generated By:JJTree: Do not edit this line. ASTparse_PortRoleDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_PortRoleDescription extends SimpleNode {
  public ASTparse_PortRoleDescription(int id) {
    super(id);
  }

  public ASTparse_PortRoleDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1ac67695ee27ddb1528dfe452afe7b5 (do not edit this line) */
