/* Generated By:JJTree: Do not edit this line. ASTparse_GroupDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparse_GroupDescription extends SimpleNode {
  public ASTparse_GroupDescription(int id) {
    super(id);
  }

  public ASTparse_GroupDescription(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7756c8c05e87a2ab664fc5cb5c8549a0 (do not edit this line) */
