/* Generated By:JJTree: Do not edit this line. ASTQuantifiedExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTQuantifiedExpression extends SimpleNode {
  public ASTQuantifiedExpression(int id) {
    super(id);
  }

  public ASTQuantifiedExpression(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=00c56c45cbef440341662b2677834f9c (do not edit this line) */
