/* Generated By:JJTree: Do not edit this line. ASTQualifiedReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTQualifiedReference extends SimpleNode {
  public ASTQualifiedReference(int id) {
    super(id);
  }

  public ASTQualifiedReference(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e2ecbc8924a75898f086d52e708ff4a (do not edit this line) */
