/* Generated By:JJTree: Do not edit this line. ASTRolesBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRolesBlock extends SimpleNode {
  public ASTRolesBlock(int id) {
    super(id);
  }

  public ASTRolesBlock(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f19dc4ba20f15c48479abda049d31911 (do not edit this line) */
