/* Generated By:JJTree: Do not edit this line. ASTRoleDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRoleDeclaration extends SimpleNode {
  public ASTRoleDeclaration(int id) {
    super(id);
  }

  public ASTRoleDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=567a53acf57d3f6042eafd1ba52f5f9e (do not edit this line) */
