/* Generated By:JJTree: Do not edit this line. ASTRecordItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRecordItem extends SimpleNode {
  public ASTRecordItem(int id) {
    super(id);
  }

  public ASTRecordItem(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5000737e10d24bfb16dee710502b8837 (do not edit this line) */
