/* Generated By:JJTree: Do not edit this line. ASTRoleTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRoleTypeDeclaration extends SimpleNode {
  public ASTRoleTypeDeclaration(int id) {
    super(id);
  }

  public ASTRoleTypeDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6942ea3a851766e9250743f0cf65d91 (do not edit this line) */
