/* Generated By:JJTree: Do not edit this line. ASTRepresentationDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRepresentationDeclaration extends SimpleNode {
  public ASTRepresentationDeclaration(int id) {
    super(id);
  }

  public ASTRepresentationDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05f4272b5c1471d52cf14c2fbd786bb7 (do not edit this line) */
