/* Generated By:JJTree: Do not edit this line. ASTRecord.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRecord extends SimpleNode {
  public ASTRecord(int id) {
    super(id);
  }

  public ASTRecord(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f257335cb6fc7779c78649a4f0ff18e (do not edit this line) */
