/* Generated By:JJTree: Do not edit this line. ASTReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReference extends SimpleNode {
  public ASTReference(int id) {
    super(id);
  }

  public ASTReference(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e037136b1be1410242b8d5d9dea004f (do not edit this line) */
