/* Generated By:JJTree: Do not edit this line. ASTSetExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSetExpression extends SimpleNode {
  public ASTSetExpression(int id) {
    super(id);
  }

  public ASTSetExpression(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c21e1c0c6911645392b8a4c92ba9ddfd (do not edit this line) */
