/* Generated By:JJTree: Do not edit this line. ASTSequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSequence extends SimpleNode {
  public ASTSequence(int id) {
    super(id);
  }

  public ASTSequence(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21f1133565e0882235b9104271aa4ae4 (do not edit this line) */
