/* Generated By:JJTree: Do not edit this line. ASTSystemDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSystemDeclaration extends SimpleNode {
  public ASTSystemDeclaration(int id) {
    super(id);
  }

  public ASTSystemDeclaration(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68471a57514dbe6d48c0d5c2c7c8b5e2 (do not edit this line) */
