/* Generated By:JJTree: Do not edit this line. ASTSetConstructor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSetConstructor extends SimpleNode {
  public ASTSetConstructor(int id) {
    super(id);
  }

  public ASTSetConstructor(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0db9ec33693d0320d3884992cd922ea (do not edit this line) */
