/* Generated By:JJTree: Do not edit this line. ASTSequenceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSequenceType extends SimpleNode {
  public ASTSequenceType(int id) {
    super(id);
  }

  public ASTSequenceType(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21b3dae267ec5ec43e458fb1c6637263 (do not edit this line) */
