/* Generated By:JJTree: Do not edit this line. ASTSystemStructure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSystemStructure extends SimpleNode {
  public ASTSystemStructure(int id) {
    super(id);
  }

  public ASTSystemStructure(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8b9417cf6cac305364974dd12d3866c (do not edit this line) */
