/* Generated By:JJTree: Do not edit this line. ASTSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSet extends SimpleNode {
  public ASTSet(int id) {
    super(id);
  }

  public ASTSet(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe6167b1984191fc58a38ea1eeeea925 (do not edit this line) */
