/* Generated By:JJTree: Do not edit this line. ASTSignature.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSignature extends SimpleNode {
  public ASTSignature(int id) {
    super(id);
  }

  public ASTSignature(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a7db22c6a37ef918fbbf6f431af79c0 (do not edit this line) */
