/* Generated By:JJTree: Do not edit this line. ASTSetType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSetType extends SimpleNode {
  public ASTSetType(int id) {
    super(id);
  }

  public ASTSetType(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f1ecbc08e6167891db60b0507f18f83 (do not edit this line) */
