/* Generated By:JJTree: Do not edit this line. ASTSystemBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSystemBody extends SimpleNode {
  public ASTSystemBody(int id) {
    super(id);
  }

  public ASTSystemBody(acmeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d5967181a34baa0a410c9218bef7c83 (do not edit this line) */
